name: GitHub Action
# when a Github action should run
# says run on github push
# can also run on pull_request, deployment_status
on: [push]

jobs:
  build-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - run: node -v
      - name: Install node_modules
        run: yarn
      # - name: Build the project
      #   run: yarn build
